### ISSUE TITLE
How to create a list of packages to be installed to run a given application stack [13pt]

### ISSUE THREAD

**Issue by goern** [thoth-station/core#241]
As a Container Image builder
I want to create a container image,
so that all RPM, Python Modules are installed to run the software stack

Example: get an alpine container, analyse what it runs/entrypoint, figure out which rpm we need....

Do we need to online profile an application stack to also capture dynamically loaded libraries? Can we scan/analyse offline?

Goal: create a report of
1. the dependency tree
2. source of dependencies
3. fingerprint of dependencies

Extended Goal:
1. map report results to Red Hat packages and thoth advises

**Comment by KPostOffice** [comment]
@goern I've been thinking about this off and on, but I am having trouble thinking of a reliable way to come up with this list. If the image builder can't trust the list it will likely mean that they have to verify the dependencies anyway and wouldn't save them very much time or effort.

I think in order for the feature to be useful we need to be able to reliably provide the user with **all** dependencies so that they don't have unexpected runtime errors and I don't know if this is manageable.

**Comment by KPostOffice** [comment]
One way to partially solve this is by looking at a binary file's symbol table and associating each symbol with a shared object library. This can be done statically. However, what this misses is the libraries which are loaded at runtime using dlload(). Running the binary and watching for this call will catch some calls, but there can be no guarantees that all packages have been discovered without 100% code coverage.
