### ISSUE TITLE
Have auto generated page with all images provided by thoth service

### ISSUE THREAD

**Issue by pacospace** [thoth-station/core#294]
**Is your feature request related to a problem? Please describe.**
As Thoth User,
I want to have a look at one web page on https://thoth-station.ninja/ ,
so that it will list all images provided by Thoth service,
and so that the major package of the PS (Pipfile?) are displayed

**Describe the solution you'd like**
Have an auto-generated page with all images provided by thoth service (prefixed `ps-`)
- [ ] propose location on website where the 'image creation service' shall be described, as part of that service we describe all the image's contents @pacospace 
- [ ] create CronJob to generate MD based on repo description, Pipfile, ..., ??? @pacospace 
- [ ] extend CronJob to generate HTML docs from MD @harshad16 
- [ ] create a tekton task to get information from container image and add annotations to an ImageStream[Tag] @harshad16 

**Describe alternatives you've considered**
n/a

**Additional context**
* we could also replicate this information into an ImageStream

**Comment by harshad16** [comment]
This task may take more time, as Gregory has more tasks on hand.

**Comment by fridex** [comment]
From the design point of view, it would be great to create a page that consumes data from API endpoints rather than creating a tekton task for extracting information from a repo to markdown and subsequently to HTML. There are also other advantages of consuming data from API endpoints:

* thoth can provide additional information about these images - what package versions are available, what shared objects are present in them, how to consume them, and other aspects of these container images for users (and machines later on)
* this information will be exposed to users instantly once thoth analyzes these images (which is immediately as AICoE-CI builds them)
* having an interactive overview of container images and their content might be good for users and API endpoints can still be exposed providing required information
* later, we can match package information (package specific information from analyzers and solvers) with container images that provide packages

We already have `/s2i/python` endpoint that exposes information about Python s2i. We can redesign endpoints so that they keep additional metadata needed for the page (or add as required) to list other images (e.g. jupyter notebooks).

**Comment by goern** [comment]
@fridex are you proposing an informational "Images we deliver" microservice?

**Comment by goern** [comment]
seealso https://chat.google.com/room/AAAAVjnVXFk/VZ0XU6CE0mI

**Comment by pacospace** [comment]
cc @harshad16, https://github.com/thoth-station/thoth-application/issues/1851

**Comment by goern** [comment]
any updates on this?
